### ISSUE TITLE
Support for CSS3 rotation and/or closing quotation

### ISSUE THREAD

**Issue by corradomatt** [reduxframework/elusive-iconfont#66]
Any reason why this doesn't work? I can get rotation to work with font awesome icons but it doesn't work with elusive.

I'm actually looking for this functionality because I want to have a closing quotation mark...elusive doesn't have this. If you could add the 180 rotated version of **el-icon-quotes** that would be awesome!

_love the icons btw_

**Comment by dovy** [comment]
We're looking for someone to assist us in beefing up the Elusive codebase if you're interested.  ;)

**Comment by corradomatt** [comment]
Sorry, I just don't have the time these days. I would check with some of the WordPress meetup or facebook groups. Good luck!
