### ISSUE TITLE
Icon Request: Plurk

### ISSUE THREAD

**Issue by hsbchk** [reduxframework/elusive-iconfont#77]
Plurk is one of the favorite Social Media in Taiwan, It should be good if we can have Plurk in the iconfont pack. Thank You!

http://www.plurk.com/

**Comment by dovy** [comment]
That's an odd logo, the society one. Hah.

**Comment by dovy** [comment]
We're finally back in gear. Your two icons have been added as plurk, and plurk-alt (or plurk-old).

http://elusiveicons.com/whats-new/
