### ISSUE TITLE
Some font icons not displaying

### ISSUE THREAD

**Issue by streamworksaudio** [reduxframework/elusive-iconfont#86]
Hi,

My theme comes with a plugin that is using the Redux Framework to control it's settings, and some of the options/settings are using Elusive Fonts, however recently I noticed that some of them are not displaying (I am only getting box icons).

The ones that are not display are:

el el-arrow-up icon-large
el el-arrow-right icon-large
el el-arrow-down icon-large
el el-arrow-left icon-large

These were working fine before, I have not updated anything on the theme nor plugin.  It is the plugin that loads the Redux Framework and the Elusive fonts.  For the life of me I cannot understand why these fonts won't display anymore.

I should add that this is a problem on Chrome as well as Safari.

Cheers

**Comment by kprovance** [comment]
Answered in #3063
